### ISSUE TITLE
Origin override

### ISSUE THREAD

**Issue by alanclarke** [AceMetrix/connect-cas#39]
the origin function in util is populated from the request object, however the service itself might be operating behind a load balancer (a common pattern for nodejs apps) and so it would be nice if this behaviour could be overridden to support that use case?

**Comment by badunk** [comment]
The standard way to handle proxies in express is to set the trust proxy flag: http://expressjs.com/guide/behind-proxies.html

When that is set, it will trust any X-Forwarded headers including the X-Forwarded-Proto header which you're looking for.

Let me know if this works

**Comment by alanclarke** [comment]
so it gets a bit complicated because our app is sits behind a load balancer but is also a proxy, so it would be ideal if there was a way of doing this while preserving the original request headers

**Comment by badunk** [comment]
Most proxies should have a setting to turn on those X forwarded headers.
The values of those headers are the values of the original request coming
from the client.  If the setting is turned on, req.client would refer to
the original request HTTPS I presume in your case

**Comment by alanclarke** [comment]
@badunk works like a charm, thanks!

**Comment by badunk** [comment]
no problem :+1:
