### ISSUE TITLE
Overriding configuration

### ISSUE THREAD

**Issue by iliuta** [AceMetrix/connect-cas#42]
Hi, 

I'm struggling with the serviceValidate.
In my configuration, I have a public URL for the login page (https://public_host/cas/login) and a private one (http://private_host/cas/serviceValidate) for validating tickets.

In the documentation I could read that it's possible to override all properties.

So, I write the following:

app.use('/', cas.serviceValidate({'host':'private_host', 'protocol':'http'}), cas.authenticate(), myRoute);

However, https://public_host/cas/serviceValidate is still called when validating tickets.

When I look to the code of service-validate.js I see the following line:

var options = _.extend({}, overrides, configuration);

If I change it like this (by switching overrides and configuration):
var options = _.extend({}, configuration, overrides);

it works!

The same is in authenticate.js and others. 
Is that a bug or it is supposed to work like this?

If it's a bug, I'll be happy to make a pull request. 

If not, how can I override the configuration properly in order to call my private internal serviceValidate url?

**Comment by DylanFC** [comment]
Looks like a bug to me, submit a pull request :)

**Comment by badunk** [comment]
thanks

**Comment by iliuta** [comment]
Thanks!
