### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by vaggelis2018** [AceMetrix/connect-cas#52]
After a successful login to cas, i get this error in console :: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
and then it loads a page which says unathorized.
Any help with this?

**Comment by badunk** [comment]
I'm not entirely sure, but I'm guessing this is something on your express server, outside of this module, downstream in your middleware.

Start removing middleware from your express stack to find the culprit.  One of them is sending sendHeaders while another one downstream is trying to send additional headers.

**Comment by vaggelis2018** [comment]
@badnuk After some console logs in your code I think it is coming from failed ssl verification. Can we have an optio to disable it for development?

**Comment by badunk** [comment]
I think this still might work: https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
```

**Comment by vaggelis2018** [comment]
i ll try this on Monday thanks man.
